# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-docker-image:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "build docker image"
          command: "docker build . -t node-sample"
      - run:
          name: "run docker"
          command: "docker run -d -p8080:8080 node-sample"
      - run:
          name: "test 8080 port"
          command: 'curl -s -o /dev/null -w "%{http_code}" localhost:8080'

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  docker-image-workflow:
    jobs:
      - build-docker-image
